name: aoti-cross-compile-windows

on:
  push:
    tags:
      - ciflow/inductor/*
  workflow_dispatch:
  schedule:
    # Run every 12 hours
    - cron: 30 2,14 * * *

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  get-label-type:
    name: get-label-type
    uses: pytorch/pytorch/.github/workflows/_runner-determinator.yml@main
    if: ${{ (github.event_name != 'schedule' || github.repository == 'pytorch/pytorch') && github.repository_owner == 'pytorch' }}
    with:
      triggering_actor: ${{ github.triggering_actor }}
      issue_owner: ${{ github.event.pull_request.user.login || github.event.issue.user.login }}
      curr_branch: ${{ github.head_ref || github.ref_name }}
      curr_ref_type: ${{ github.ref_type }}
      opt_out_experiments: lf

  # Step 1:
  # Build PyTorch on Windows. Cross-compile on Linux will require libtorch_cpu.dll and libtorch_cuda.dll.
  windows-test-build:
    name: windows-test-build
    uses: ./.github/workflows/_win-build.yml
    needs: get-label-type
    with:
      build-environment: win-vs2022-cuda12.8-py3.10
      cuda-version: "12.8"
      test-matrix: |
        { include: [
          { config: "aoti_cross_compile_run_on_windows", shard: 1, num_shards: 1, runner: "windows.g5.4xlarge.nvidia.gpu" },
        ]}
    secrets: inherit

  # Build PyTorch on Linux. Using CUDA 12.8 so that we don't have to build another image.
  cross-compile-linux-build:
    name: inductor-build
    uses: ./.github/workflows/_linux-build.yml
    needs: get-label-type
    with:
      build-environment: linux-jammy-cuda12.8-py3.10-gcc9-sm86
      docker-image-name: ci-image:pytorch-linux-jammy-cuda12.8-cudnn9-py3-gcc9-inductor-benchmarks
      cuda-arch-list: '8.6'
      runner_prefix: "${{ needs.get-label-type.outputs.label-type }}"
      test-matrix: |
        { include: [
          { config: "aoti_cross_compile_for_windows", shard: 1, num_shards: 1, runner: "${{ needs.get-label-type.outputs.label-type }}linux.g5.4xlarge.nvidia.gpu" },
        ]}
    secrets: inherit

  # Step 2: Cross-compile models on Linux
  cross-compile-linux-test:
    name: cross-compile-linux-test
    uses: ./.github/workflows/_linux-test.yml
    needs: [cross-compile-linux-build, windows-test-build]
    with:
      build-environment: linux-jammy-cuda12.8-py3.10-gcc9-sm86
      docker-image: ${{ needs. cross-compile-linux-build.outputs.docker-image }}
      test-matrix: ${{ needs. cross-compile-linux-build.outputs.test-matrix }}
    secrets: inherit

  # Step 3: Test compiled packages on Windows
  windows-test:
    name: windows-test
    runs-on: windows.g5.4xlarge.nvidia.gpu
    needs: [windows-test-build, cross-compile-linux-test]
    timeout-minutes: 240
    if: success()
    defaults:
      run:
        shell: bash
    steps:
      - name: Enable git long paths and symlinks on Windows and disable fsmonitor daemon
        shell: bash
        run: |
          git config --global core.longpaths true
          git config --global core.symlinks true
          git config --global core.ignorecase false
          git config --global core.fsmonitor false

      - name: Setup SSH (Click me for login details)
        uses: pytorch/test-infra/.github/actions/setup-ssh@main
        with:
          github-secret: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout PyTorch
        uses: pytorch/pytorch/.github/actions/checkout-pytorch@main
        with:
          no-sudo: true

      - name: Setup Windows
        uses: ./.github/actions/setup-win
        with:
          cuda-version: "12.8"

      - name: Download PyTorch Build Artifacts
        uses: seemethere/download-artifact-s3@v4
        with:
          name: win-vs2022-cuda12.8-py3.10
          path: C:\${{ github.run_id }}\build-results

      - name: Download AOTI packages from S3
        uses: seemethere/download-artifact-s3@v4
        with:
          s3-bucket: gha-artifacts
          s3-prefix: ${{ github.repository }}/${{ github.run_id }}/artifacts/aoti-cross-compile
          path: D:\aoti_packages

      - name: Verify packages
        shell: bash
        run: |
          echo "Build artifacts:"
          ls -la "C:/${{ github.run_id }}/build-results/" || echo "No build artifacts found"
          echo "AOTI packages:"
          ls -la "D:/aoti_packages/" || echo "No AOTI packages found"

      - name: Run Windows load tests
        shell: bash
        env:
          USE_CUDA: 1
        run: |
          # Run Windows load tests with downloaded packages
          python test/inductor/test_aoti_cross_compile_windows.py -k load --package-dir D:/aoti_packages
