name: rocm

on:
  push:
    branches:
      - main
      - release/*
    tags:
      - ciflow/rocm/*
  workflow_dispatch:
  schedule:
    - cron: 29 8 * * *  # about 1:29am PDT

#concurrency: #commented out to allow for multiple workflow runs of this workflow.
  #group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}
  #cancel-in-progress: false

permissions: read-all

jobs:
  target-determination:
    if: github.repository_owner == 'pytorch'
    name: before-test
    uses: ./.github/workflows/target_determination.yml
    permissions:
      id-token: write
      contents: read

  linux-jammy-rocm-py3_10-build:
    if: ${{ (github.event_name != 'schedule' || github.repository == 'pytorch/pytorch') && github.repository_owner == 'pytorch' }}
    name: linux-jammy-rocm-py3.10
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-jammy-rocm-py3.10
      docker-image-name: ci-image:pytorch-linux-jammy-rocm-n-py3
      sync-tag: rocm-build
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 18, runner: "linux.rocm.gpu.mi250.1" },
          { config: "default", shard: 2, num_shards: 18, runner: "linux.rocm.gpu.mi250.1" },
          { config: "default", shard: 3, num_shards: 18, runner: "linux.rocm.gpu.mi250.1" },
          { config: "default", shard: 4, num_shards: 18, runner: "linux.rocm.gpu.mi250.1" },
          { config: "default", shard: 5, num_shards: 18, runner: "linux.rocm.gpu.mi250.1" },
          { config: "default", shard: 6, num_shards: 18, runner: "linux.rocm.gpu.mi250.1" },
          { config: "default", shard: 7, num_shards: 18, runner: "linux.rocm.gpu.mi250.1" },
          { config: "default", shard: 8, num_shards: 18, runner: "linux.rocm.gpu.mi250.1" },
          { config: "default", shard: 9, num_shards: 18, runner: "linux.rocm.gpu.mi250.1" },
          { config: "default", shard: 10, num_shards: 18, runner: "linux.rocm.gpu.mi250.1" },
          { config: "default", shard: 11, num_shards: 18, runner: "linux.rocm.gpu.mi250.1" },
          { config: "default", shard: 12, num_shards: 18, runner: "linux.rocm.gpu.mi250.1" },
          { config: "default", shard: 13, num_shards: 18, runner: "linux.rocm.gpu.mi250.1" },
          { config: "default", shard: 14, num_shards: 18, runner: "linux.rocm.gpu.mi250.1" },
          { config: "default", shard: 15, num_shards: 18, runner: "linux.rocm.gpu.mi250.1" },
          { config: "default", shard: 16, num_shards: 18, runner: "linux.rocm.gpu.mi250.1" },
          { config: "default", shard: 17, num_shards: 18, runner: "linux.rocm.gpu.mi250.1" },
          { config: "default", shard: 18, num_shards: 18, runner: "linux.rocm.gpu.mi250.1" },
        ]}
    secrets: inherit

  linux-jammy-rocm-py3_10-test:
    permissions:
      id-token: write
      contents: read
    name: linux-jammy-rocm-py3.10
    uses: ./.github/workflows/_rocm-test.yml
    needs:
      - linux-jammy-rocm-py3_10-build
      - target-determination
    with:
      build-environment: linux-jammy-rocm-py3.10
      docker-image: ${{ needs.linux-jammy-rocm-py3_10-build.outputs.docker-image }}
      test-matrix: ${{ needs.linux-jammy-rocm-py3_10-build.outputs.test-matrix }}
    secrets: inherit
